# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to those generated by the
# Android Gradle plugin.
# https://developer.android.com/studio/build/shrink-code
